### ISSUE TITLE
Comparison with rhusics

### ISSUE THREAD

**Issue by erlend-sh** [DataAnalysisCosby/mgf#3]
This seems quite similar to @rhuagh's [rhusics](https://github.com/Rhuagh/rhusics). I guess the main difference is:

Rhusics is:

- made for us with Specs
- also supports 2D
- uses collision-rs

Would be very helpful to have a short "Differences between mgf and {similar-projects}" paragraph or page somewhere.

**Comment by maplant** [comment]
The main difference is that rhusics depends on collision-rs.
MGF begins primarily as a continuous collision detection library, allowing the time of impact to be found for moving objects. That is where it provides novel implementations. I wouldn't say the physics component is an after thought, but at the moment it is decidedly less mature than the collision detection routines.

Overall, the goal is to provide enough tools so that making custom 3D games is easy, without having to provide any pre-defined World struct. In fact, before I released the code as-is, I included custom derives to automatically add step and collision handling routines to World structs. Unfortunately, one size fits all solutions rarely fit anybody.

I'm leaving this open until I add a good, well thought out explanation to the README

**Comment by Rhuagh** [comment]
I would say the main difference is that you seem to know this fairly well, while I started out to learn game physics about three months ago :P

**Comment by maplant** [comment]
I've only been doing 3D rigid body stuff for a similar amount of time, although I've been doing 2D simulations and collision detection for much longer, so I wouldn't say I'm extremely experienced or anything like that.

**Comment by maplant** [comment]
@erlend-sh in your opinion does the new readme do a good job of explaining the differences?

**Comment by erlend-sh** [comment]
Yep, thanks for taking the time!
